services:
  dashboard:
    build: .
    # NO ports: line anymore
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - npm-host-bridge

networks:
  npm-host-bridge:
    external: true
